### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by michaelcplusplus** [jemc/emqttd_elixir_plugin_template#1]
Is this plugin used in a production environment?
Which emqtt version ist supported?

**Comment by jemc** [comment]
No, at the moment this was just a one-time exploration of whether it is possible to use elixir in an emqtt plugin.

I have not used this in a production environment, and I have not used it at all recently.

It's up on GitHub in case it helps anyone else, and I'll happily accept pull requests, but I'm not actively involved with this project at all at this time.  I'm not even using emqtt in any capacity at the moment.
